#ifndef LOQUAT_REVISION_H_INC
#define LOQUAT_REVISION_H_INC

#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_PATCH 0
#define VERSION_BUILD 0

#define STR_HELP(x) #x
#define STR(x) STR_HELP(x)

#define VERSION_FILEVERSION VERSION_MAJOR,VERSION_MINOR,VERSION_PATCH,VERSION_BUILD
#define VERSION_FILEVERSION_STR STR(VERSION_MAJOR) "." STR(VERSION_MINOR) "." STR(VERSION_PATCH) "." STR(VERSION_BUILD)
#define VERSION_COPYRIGHT_STR "\xA9 2023-2024"

#ifdef NDEBUG
#define VERSION_ORIGINAL_FILENAME_STR "loquat-vc143-mt.dll"
#else
#define VERSION_ORIGINAL_FILENAME_STR "loquat-vc143-mt.dll"
#endif // NDEBUG

#endif // LOQUAT_REVISION_H_INC
