#pragma once

#ifdef _LOQUAT_WIN32
	#include "platform/windows/platform_win32.h"
#else
	#define LOQUAT_WIN32_WINDOW_STATE
	#define LOQUAT_WIN32_MONITOR_STATE
	#define LOQUAT_WIN32_CURSOR_STATE
#endif // _LOQUAT_WIN32

#ifdef _LOQUAT_WAYLAND
#else
	#define LOQUAT_WAYLAND_WINDOW_STATE
	#define LOQUAT_WAYLAND_MONITOR_STATE
	#define LOQUAT_WAYLAND_CURSOR_STATE
#endif // _LOQUAT_WAYLAND

#ifdef _LOQUAT_X11
#else
	#define LOQUAT_X11_WINDOW_STATE
	#define LOQUAT_X11_MONITOR_STATE
	#define LOQUAT_X11_CURSOR_STATE
#endif // _LOQUAT_X11
